let resList = [
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "21101",
          name: "The Great Punjabi Dhaba and Caterers",
          uuid: "9d16f9ef-4732-4de1-8d4b-c8d56d4dd0fe",
          city: "4",
          area: "Rohini",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "bobgejyxxdyhmzlcuvfj",
          cuisines: [
            "Mughlai",
            "North Indian",
            "Chinese",
            "Biryani",
            "Kebabs",
            "Snacks",
            "American",
          ],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          slaString: "28 MINS",
          lastMileTravel: 4.699999809265137,
          slugs: {
            restaurant: "the-great-punjabi-dhaba-and-caterers-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address: "G-10, RG Complex 2, Sector 14, Prashant Vihar, Delhi ",
          locality: "Sector 9",
          parentId: 14159,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "FLAT125 off",
            shortDescriptionList: [
              {
                meta: "FLAT125 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT125 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹125 OFF",
            shortDescriptionList: [
              {
                meta: "Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT125 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 4000,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 4000,
            message: "",
            title: "Delivery Charge",
            amount: "4000",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=6341585~p=19~eid=00000187-40b1-d3df-141a-215900b01377",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4.6 kms",
          hasSurge: false,
          sla: {
            restaurantId: "21101",
            deliveryTime: 28,
            minDeliveryTime: 28,
            maxDeliveryTime: 28,
            lastMileTravel: 4.699999809265137,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "3.8",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "57964",
          name: "Nivetha Dosa Corner",
          uuid: "075ee25c-aac4-47e7-85a2-f0f12c747486",
          city: "4",
          area: "Rohini",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "sl5zjhhb74jycp1ezsqa",
          cuisines: ["South Indian"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          slaString: "21 MINS",
          lastMileTravel: 1.2000000476837158,
          slugs: {
            restaurant: "nivetha-dosa-corner-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address: "Shop 349, Block A 1, Dividing Road 6 & 7, Rohini, New Delhi",
          locality: "1St Block",
          parentId: 16722,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.2 kms",
          hasSurge: false,
          sla: {
            restaurantId: "57964",
            deliveryTime: 21,
            minDeliveryTime: 21,
            maxDeliveryTime: 21,
            lastMileTravel: 1.2000000476837158,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.0",
          totalRatings: 5000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "676590",
          name: "Chinese Tadka\t",
          uuid: "2a1ca485-c4aa-4565-9cdf-db32372f8c88",
          city: "4",
          area: "Rohini",
          totalRatingsString: "Too Few Ratings",
          cloudinaryImageId: "236152bfc9b3945b4a368e55fb3def62",
          cuisines: ["Chinese", "Snacks", "Burgers"],
          tags: [],
          costForTwo: 15000,
          costForTwoString: "₹150 FOR TWO",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          slaString: "26 MINS",
          lastMileTravel: 0.4000000059604645,
          slugs: {
            restaurant: "chinese-tadka-rohini-rohini-3",
            city: "delhi",
          },
          cityState: "4",
          address:
            "B-101, Vijay Vihar, Vijay Vihar Phase II, Gopal Vihar, Sector 1, Rohini, Delhi, 110085, India",
          locality: "Vijay Vihar",
          parentId: 4483,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.4 kms",
          hasSurge: false,
          sla: {
            restaurantId: "676590",
            deliveryTime: 26,
            minDeliveryTime: 26,
            maxDeliveryTime: 26,
            lastMileTravel: 0.4000000059604645,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "--",
          totalRatings: 0,
          new: true,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "36877",
          name: "Creme N Crisp",
          uuid: "a3aca518-c9c3-4b75-b8bb-4179a17c32b6",
          city: "4",
          area: "Paschim Vihar",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "yyonxol9dn4luucdfkh6",
          cuisines: ["Desserts", "Bakery", "Sweets"],
          tags: [],
          costForTwo: 50000,
          costForTwoString: "₹500 FOR TWO",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          slaString: "31 MINS",
          lastMileTravel: 4.800000190734863,
          slugs: {
            restaurant: "creme-n-crisp-paschim-vihar-punjabi-bagh",
            city: "delhi",
          },
          cityState: "4",
          address:
            "A6/8, Ground Floor, East Paschim Vihar, Near Paschim Vihar, New Delhi",
          locality: "Chaudhary Balbir Singh Marg",
          parentId: 2070,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "20% off",
            shortDescriptionList: [
              {
                meta: "20% off | Use PARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "20% off | Use code PARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "20% OFF",
            shortDescriptionList: [
              {
                meta: "Use PARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "20% off | Use code PARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 4000,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 4000,
            message: "",
            title: "Delivery Charge",
            amount: "4000",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=6398464~p=22~eid=00000187-40b1-d3df-141a-215a00b01659",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "36877",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            lastMileTravel: 4.800000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.0",
          totalRatings: 5000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "633796",
          name: "Bolgatty Palace",
          uuid: "36be4d16-3e0f-4dbd-854d-46a493a16837",
          city: "4",
          area: "Rohini",
          totalRatingsString: "50+ ratings",
          cloudinaryImageId: "mcaqrphbrgzqsq34cx1j",
          cuisines: ["North Indian"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 17,
          minDeliveryTime: 17,
          maxDeliveryTime: 17,
          slaString: "17 MINS",
          lastMileTravel: 1.399999976158142,
          slugs: {
            restaurant: "bolgatty-palace-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address: "82,ground floor, block c,pkt-4,sector 6,rohini,delhi",
          locality: "Sector 6",
          parentId: 381017,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.3 kms",
          hasSurge: false,
          sla: {
            restaurantId: "633796",
            deliveryTime: 17,
            minDeliveryTime: 17,
            maxDeliveryTime: 17,
            lastMileTravel: 1.399999976158142,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.7",
          totalRatings: 50,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "336053",
          name: "Wendy's Burgers",
          uuid: "b07bfcc5-8dce-49e6-9874-58712ce60c01",
          city: "4",
          area: "Pushpanjali",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "aab4bc89ce4991a11400733e48ec21d1",
          cuisines: ["American", "Burgers", "Fast Food", "Beverages", "Snacks"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          slaString: "26 MINS",
          lastMileTravel: 2.5999999046325684,
          slugs: {
            restaurant: "wendys-sector-8-rohini",
            city: "delhi",
          },
          cityState: "4",
          address:
            "Plot 8, Ground Floor, Sachdeva Tower Sector 8, Rohini, New Delhi 110085",
          locality: "Sector 8",
          parentId: 972,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=6391800~p=25~eid=00000187-40b1-d3df-141a-215b00b01919",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "2.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "336053",
            deliveryTime: 26,
            minDeliveryTime: 26,
            maxDeliveryTime: 26,
            lastMileTravel: 2.5999999046325684,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.0",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "432396",
          name: "Bansi Wala",
          uuid: "c30edeca-94a2-4086-9424-1e007a2c39ec",
          city: "4",
          area: "Rohini",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "xghsu7ngyzloge1eifii",
          cuisines: ["North Indian", "Snacks", "Chinese", "Bakery"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 16,
          minDeliveryTime: 16,
          maxDeliveryTime: 16,
          slaString: "16 MINS",
          lastMileTravel: 0.800000011920929,
          slugs: {
            restaurant: "bansiwala-rohini-rohini-4",
            city: "delhi",
          },
          cityState: "4",
          address:
            "58, Ground Floor, Bhock-H, Pocket-33, Sector-3, Rohini, Delhi-110085",
          locality: "Sector 3",
          parentId: 6840,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "10% off",
            shortDescriptionList: [
              {
                meta: "10% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "10% off up to ₹40 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "10% OFF",
            shortDescriptionList: [
              {
                meta: "Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "10% off up to ₹40 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "432396",
            deliveryTime: 16,
            minDeliveryTime: 16,
            maxDeliveryTime: 16,
            lastMileTravel: 0.800000011920929,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.1",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "146526",
          name: "Veerji Malai Chaap Wale (Rohini)",
          uuid: "e77ac1d3-dfbf-4338-bb45-eb7916a9fd2e",
          city: "4",
          area: "Rohini",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "n0zsyorrb51ogrtdrkx9",
          cuisines: ["North Indian", "Snacks"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          slaString: "29 MINS",
          lastMileTravel: 0.800000011920929,
          slugs: {
            restaurant: "veer-ji-malai-chaap-rohini",
            city: "delhi",
          },
          cityState: "4",
          address:
            "Shop no 1, Block F, Pocket 24, Sector 7, Rohini, North West, Delhi- 110085",
          locality: "Sector 7",
          parentId: 16511,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "40% off",
            shortDescriptionList: [
              {
                meta: "40% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "40% off up to ₹80 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "40% OFF",
            shortDescriptionList: [
              {
                meta: "Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "40% off up to ₹80 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "146526",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            lastMileTravel: 0.800000011920929,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.8",
          totalRatings: 5000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "330354",
          name: "MADRAS CAFE",
          uuid: "634cba1d-8a00-485a-98b9-70d356dd0f26",
          city: "4",
          area: "Rohini",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "xaqdcwc6k6uepb7lww2i",
          cuisines: ["South Indian"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          slaString: "21 MINS",
          lastMileTravel: 1.100000023841858,
          slugs: {
            restaurant: "madras-café-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address: "D-14/160, SECTOR-3, ROHINI,  North West , Delhi-110085",
          locality: "Sector 3",
          parentId: 612,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "10% off",
            shortDescriptionList: [
              {
                meta: "10% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "10% off up to ₹40 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "10% OFF",
            shortDescriptionList: [
              {
                meta: "Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "10% off up to ₹40 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.1 kms",
          hasSurge: false,
          sla: {
            restaurantId: "330354",
            deliveryTime: 21,
            minDeliveryTime: 21,
            maxDeliveryTime: 21,
            lastMileTravel: 1.100000023841858,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.7",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "225792",
          name: "Cake Studio-100% Veg",
          uuid: "eb898b48-64e9-4b5b-a562-273bfcc93c80",
          city: "4",
          area: "Rohini",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "206068b31aab7c1b78fa24e2745d153d",
          cuisines: ["Bakery", "Desserts"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          slaString: "22 MINS",
          lastMileTravel: 0.800000011920929,
          slugs: {
            restaurant: "cake-studio-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address: "B-948, sector 1,rohini Avantika. ( Near masjid,) new delhi",
          locality: "Sector 1",
          parentId: 15057,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "FLAT125 off",
            shortDescriptionList: [
              {
                meta: "FLAT125 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT125 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹125 OFF",
            shortDescriptionList: [
              {
                meta: "Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT125 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "225792",
            deliveryTime: 22,
            minDeliveryTime: 22,
            maxDeliveryTime: 22,
            lastMileTravel: 0.800000011920929,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.8",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "587988",
          name: "SGF - Spice Grill Flame (Avantika)",
          uuid: "1c7c3580-b7b3-43ba-a5bb-8ca4838ab5c7",
          city: "4",
          area: "Rohini",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "lrwzcus68r0ecjnvvvkw",
          cuisines: ["North Indian", "Chinese", "Snacks"],
          tags: [],
          costForTwo: 35000,
          costForTwoString: "₹350 FOR TWO",
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          slaString: "19 MINS",
          lastMileTravel: 0.5,
          slugs: {
            restaurant: "spice-grill-flame-(avantika)-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address:
            "H.no. 102, ground floor , pocket -22, sector -3, near avantika chowk , rohini, delhi , mangolpuri khurd, rohini , north west, delhi-110085",
          locality: "avantika chowk",
          parentId: 351839,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "Free Spring Roll",
            shortDescriptionList: [
              {
                meta: "Free Spring Roll on orders above ₹479",
                discountType: "Freebie",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Free Spring Roll on orders above ₹479",
                discountType: "Freebie",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "60% OFF",
            shortDescriptionList: [
              {
                meta: "Free Spring Roll",
                discountType: "Freebie",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Free Spring Roll on orders above ₹479",
                discountType: "Freebie",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "587988",
            deliveryTime: 19,
            minDeliveryTime: 19,
            maxDeliveryTime: 19,
            lastMileTravel: 0.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.0",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "232802",
          name: "The Burger Club",
          uuid: "c7c2f87e-9311-4844-9867-052b96de2cc0",
          city: "4",
          area: "Rohini",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "xivxfyvnqem6spp5rjwz",
          cuisines: ["American", "Beverages", "Desserts"],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          slaString: "24 MINS",
          lastMileTravel: 3,
          slugs: {
            restaurant: "burger-club-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address: "PROPERTY NO. 4 BLOCK-C POCKET-9 SECTOR-7 ROHINI",
          locality: "Sector 7",
          parentId: 2285,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "Flat ₹125 off",
            shortDescriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹125 OFF",
            shortDescriptionList: [
              {
                meta: "Use MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 4000,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 4000,
            message: "",
            title: "Delivery Charge",
            amount: "4000",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "3 kms",
          hasSurge: false,
          sla: {
            restaurantId: "232802",
            deliveryTime: 24,
            minDeliveryTime: 24,
            maxDeliveryTime: 24,
            lastMileTravel: 3,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.2",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "46868",
          name: "Kushal Bhojnalaya",
          uuid: "06113b5f-050c-42b7-89f6-984ebba2c500",
          city: "4",
          area: "Rohini",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "ziut33ivgwn3pygy7rfo",
          cuisines: ["North Indian"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          slaString: "19 MINS",
          lastMileTravel: 0.800000011920929,
          slugs: {
            restaurant: "kushal-bhojnalaya-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address: "S 6 14  CSC 4  DDA Market  Sector 2  Rohini  New Delhi",
          locality: "Sector 2",
          parentId: 16754,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "46868",
            deliveryTime: 19,
            minDeliveryTime: 19,
            maxDeliveryTime: 19,
            lastMileTravel: 0.800000011920929,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.2",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "40415",
          name: "Bikanervala",
          uuid: "19c157ee-1076-4bc1-8980-a5b689f7312f",
          city: "4",
          area: "Rohini",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "bhb6fmjbetmpa2nh3w0t",
          cuisines: ["North Indian", "Snacks", "Chaat", "Sweets"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          slaString: "24 MINS",
          lastMileTravel: 2,
          slugs: {
            restaurant: "bikanervala-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address: "G-9, Ring Road Mall, Rohini, New Delhi",
          locality: "Ring Road",
          parentId: 45936,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "2 kms",
          hasSurge: false,
          sla: {
            restaurantId: "40415",
            deliveryTime: 24,
            minDeliveryTime: 24,
            maxDeliveryTime: 24,
            lastMileTravel: 2,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.3",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "10325",
          name: "Pizzallo Hot",
          uuid: "92d459c9-ba78-4247-aa7c-70d85c8e06b1",
          city: "4",
          area: "Rohini",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "q4cumlrajxgrsrod3asn",
          cuisines: ["Pizzas", "Italian"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          slaString: "25 MINS",
          lastMileTravel: 0.5,
          slugs: {
            restaurant: "m-pizzallo-hot-sector-3-near-gopal-chole-bhature-rohini",
            city: "delhi",
          },
          cityState: "4",
          address: "F 22/1, Rohini Sector 3, Near Gopal Chole Bhature",
          locality: "Sector 3",
          parentId: 159117,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "FLAT100 off",
            shortDescriptionList: [
              {
                meta: "FLAT100 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT100 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹100 OFF",
            shortDescriptionList: [
              {
                meta: "Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT100 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "0.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "10325",
            deliveryTime: 25,
            minDeliveryTime: 25,
            maxDeliveryTime: 25,
            lastMileTravel: 0.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.6",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "348417",
          name: "VARIATION (Rohini)",
          uuid: "f21912ae-9277-4972-b60b-b59271bbc53f",
          city: "4",
          area: "Rohini",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "sjkmybxus7kvcuyentst",
          cuisines: ["Chinese", "Beverages"],
          tags: [],
          costForTwo: 35000,
          costForTwoString: "₹350 FOR TWO",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          slaString: "24 MINS",
          lastMileTravel: 1,
          slugs: {
            restaurant: "variation-(rohini)-rohini-rohini",
            city: "delhi",
          },
          cityState: "4",
          address:
            "PROP.NO-19, BLOCK AND POCKET D-15, SECTOR-3 ROHINI DELHI, RITHALA, Rohini, North West   , Delhi-110085",
          locality: "3Rd Sector ",
          parentId: 221459,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1 kms",
          hasSurge: false,
          sla: {
            restaurantId: "348417",
            deliveryTime: 24,
            minDeliveryTime: 24,
            maxDeliveryTime: 24,
            lastMileTravel: 1,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.9",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
  ];

  export default resList;